package tests;

import automate.Evolution;
import automate.Grille;
import automate.GrilleAnnulable;
import automate.GrilleCirculaire;
import visu.AnimationGrille;
import visu.ImageGrille;

import static visu.ImageGrille.BLANC;
import static visu.ImageGrille.BLEU;
import static visu.ImageGrille.NOIR;
import static visu.ImageGrille.ROUGE;
import static visu.ImageGrille.VERT;

import java.io.IOException;

@SuppressWarnings("unused") // <- TODO à supprimer
public class Main {
	
	/*
	 * NOTE D'UTILISATION DU PROGRAMME DE TEST :
	 * 
	 * - faites les exercices de préférence dans l'ordre
	 * 
	 * - quand un exercice est fait décommentez le code de test correspondant dans la fonction main
	 *     
	 * - quand la trace d'exécution coïncide avec celle indiquée en commentaire,
	 *   vous pouvez passer à l'exercice suivant
	 */

	public static void main(String[] args) throws IOException {

		System.out.println("---- Exercice 1 ----\n");
/*		
		System.out.println("Test des règles de Conway :\n");
		
		for (int i=0 ; i<9 ; i++)
			System.out.println("- cellule entourée de " + i + " cellule(s) vivante(s) peut naître : " + (Evolution.CONWAY.peutNaitre(i) ? "[OUI]" : " non ") + " ; peut survivre : " + (Evolution.CONWAY.peutSurvivre(i) ? "[OUI]" : " non "));
		System.out.println();
		
		for (int i=0 ; i<9 ; i++)
			System.out.println("- cellule vivante entourée de " + i + " cellule(s) vivante(s) changera d'état : " + (Evolution.CONWAY.changeraDEtat(true, i) ? "[OUI]" : " non "));
		System.out.println();

		for (int i=0 ; i<9 ; i++)
			System.out.println("- cellule morte entourée de " + i + " cellule(s) vivante(s) changera d'état : " + (Evolution.CONWAY.changeraDEtat(false, i) ? "[OUI]" : " non "));
*/
		System.out.println("\n---- Exercice 2 ----\n");
/*
		boolean[][] init = {
				{false, true , true , false, false, true , true },
				{false, false, false, false, false, false, false},
				{false, false, false, true , true , false, false},
				{false, false, true , true , true , false, false},
				{false, false, false, false, false, false, true },				
		};
		Grille g = new Grille(init, Evolution.CONWAY);
		System.out.println("Grille " + g.NL + "x" + g.NC + " (tableau) :\n");
		System.out.println(g);
		
		g = new Grille(5, 7, 25, Evolution.CONWAY);
		System.out.println("Grille " + g.NL + "x" + g.NC + " (aléatoire, 25%) :\n");
		System.out.println(g);
		
		g = new Grille(5, 7, 75, Evolution.CONWAY);
		System.out.println("Grille " + g.NL + "x" + g.NC + " (aléatoire, 75%) :\n");
		System.out.println(g);
*/
		System.out.println("\n---- Exercice 3 ----\n");
/*
		g = new Grille(init, Evolution.CONWAY);

		System.out.println("Grille :\n");
		System.out.println(g);
		
		System.out.println("case ( 0,  0) : '" + (g.get( 0, 0) ? "O" : ".")+ "' voisins : " + g.nbcVois( 0, 0) + (g.changera( 0, 0) ? " changera" : ""));
		System.out.println("case ( 2,  2) : '" + (g.get( 2, 2) ? "O" : ".")+ "' voisins : " + g.nbcVois( 2, 2) + (g.changera( 2, 2) ? " changera" : ""));
		System.out.println("case ( 2,  3) : '" + (g.get( 2, 3) ? "O" : ".")+ "' voisins : " + g.nbcVois( 2, 3) + (g.changera( 2, 3) ? " changera" : ""));
		System.out.println("case (-1, -1) : '" + (g.get(-1,-1) ? "O" : ".")+ "' voisins : " + g.nbcVois(-1,-1) + (g.changera(-1,-1) ? " changera" : ""));
		System.out.println("case ( 5,  6) : '" + (g.get( 5, 6) ? "O" : ".")+ "' voisins : " + g.nbcVois( 5, 6) + (g.changera( 5, 6) ? " changera" : ""));
*/
		System.out.println("\n---- Exercice 4 ----\n");
/*		
		g = new Grille("clown.txt", Evolution.CONWAY);
		System.out.println("Etat initial :\n");
		System.out.println(g);
		
		System.out.println("Etape suivante (grille modifiée ? " + (g.next() ? "OUI" : "non") + ") :\n");
		System.out.println(g);
		System.out.println("Etape suivante (grille modifiée ? " + (g.next() ? "OUI" : "non") + ") :\n");
		System.out.println(g);
		System.out.println("Etape suivante (grille modifiée ? " + (g.next() ? "OUI" : "non") + ") :\n");
		System.out.println(g);
		System.out.println("Etape suivante (grille modifiée ? " + (g.next() ? "OUI" : "non") + ") :\n");
		System.out.println(g);

		g.next(106);
		System.out.println("106 étapes suivantes :\n");
		System.out.println(g);
		
		System.out.print("Sauvegarde dans clown-110.txt...");
		g.save("clown-110.txt");
		System.out.println(" ok\n");

		System.out.print("Visualisation de clown, oscillateur, galaxie, puffer, canon, floraison et grenouille...");
		
		g = new Grille("clown.txt", Evolution.CONWAY);
		ImageGrille ig = new ImageGrille("clown", g, 800, 800, 1, 2);
		AnimationGrille vg = new AnimationGrille(ig);
		vg.start();
		
		g = new Grille("oscillateur.txt", Evolution.CONWAY);
		ig = new ImageGrille("oscillateur", g, 500, 500, 2, 3);
		vg = new AnimationGrille(ig);
		vg.start();

		g = new Grille("galaxie.txt", Evolution.CONWAY);
		ig = new ImageGrille("galaxie", g, 600, 600, 2, 3);
		vg = new AnimationGrille(ig);
		vg.start();

		g = new Grille("puffeur.txt", Evolution.CONWAY);
		ig = new ImageGrille("puffeur", g, 700, 700);
		vg = new AnimationGrille(ig);
		vg.start();

		g = new Grille("canon.txt", Evolution.CONWAY);
		ig = new ImageGrille("canon", g, 520, 380, 1, 2);
		vg = new AnimationGrille(ig);
		vg.start();

		g = new Grille("floraison.txt", Evolution.CONWAY);
		ig = new ImageGrille("floraison", g, 700, 700, 8, 2, true, NOIR, BLANC, BLANC, BLEU, ROUGE, VERT);
		vg = new AnimationGrille(ig);
		vg.start();
	
		g = new Grille("grenouille.txt", Evolution.CONWAY);
		ig = new ImageGrille("grenouille", g, 400, 400, 6, 4);
		vg = new AnimationGrille(ig);
		vg.start();
		
		System.out.println(" ok\n");
*/
		System.out.println("\n---- Exercice 5 ----\n");
/*
		g = new GrilleCirculaire(init, Evolution.CONWAY);

		System.out.println("Grille :\n");
		System.out.println(g);
		
		System.out.println("case ( 0,  0) : '" + (g.get( 0, 0) ? "O" : ".")+ "' voisins : " + g.nbcVois( 0, 0) + (g.changera( 0, 0) ? " changera" : ""));
		System.out.println("case ( 2,  2) : '" + (g.get( 2, 2) ? "O" : ".")+ "' voisins : " + g.nbcVois( 2, 2) + (g.changera( 2, 2) ? " changera" : ""));
		System.out.println("case ( 2,  3) : '" + (g.get( 2, 3) ? "O" : ".")+ "' voisins : " + g.nbcVois( 2, 3) + (g.changera( 2, 3) ? " changera" : ""));
		System.out.println("case (-1, -1) : '" + (g.get(-1,-1) ? "O" : ".")+ "' voisins : " + g.nbcVois(-1,-1) + (g.changera(-1,-1) ? " changera" : ""));
		System.out.println("case ( 5,  6) : '" + (g.get( 5, 6) ? "O" : ".")+ "' voisins : " + g.nbcVois( 5, 6) + (g.changera( 5, 6) ? " changera" : ""));

		g = new Grille("planeur.txt", Evolution.CONWAY);
		System.out.println("\nGrille non circulaire, état initial :\n");
		System.out.println(g);
		
		g.next(40);
		System.out.println("40 étapes suivantes :\n");
		System.out.println(g);
		
		g = new GrilleCirculaire("planeur.txt", Evolution.CONWAY);
		System.out.println("Grille circulaire, état initial :\n");
		System.out.println(g);
		
		g.next(40);
		System.out.println("40 étapes suivantes :\n");
		System.out.println(g);
		
		System.out.print("Visualisation de planeur, mathusalem et spacefiller...");
		
		g = new GrilleCirculaire("planeur.txt", Evolution.CONWAY);
		ig = new ImageGrille("planeur", g, 700, 500);
		vg = new AnimationGrille(ig);
		vg.start();

		g = new GrilleCirculaire("mathusalem.txt", Evolution.CONWAY);
		ig = new ImageGrille("mathusalem", g, 1560, 800, 1, 2);
		vg = new AnimationGrille(ig);
		vg.start();

		g = new GrilleCirculaire("spacefiller.txt", Evolution.CONWAY);
		ig = new ImageGrille("spacefiller", g, 700, 700, 1, 1);
		vg = new AnimationGrille(ig);
		vg.start();
		
		System.out.println(" ok\n");
*/
		System.out.println("\n---- Exercice 6 ----\n");
/*
		GrilleAnnulable ga = new GrilleAnnulable("planeur.txt", Evolution.CONWAY);
		System.out.println("Etat initial :\n");
		System.out.println(ga);

		ga.next();
		System.out.println("Etape suivante :\n");
		System.out.println(ga);

		ga.next();
		System.out.println("Etape suivante :\n");
		System.out.println(ga);
		
		ga.next();
		System.out.println("Etape suivante :\n");
		System.out.println(ga);
		
		ga.prev();
		System.out.println("Etape précédente :\n");
		System.out.println(ga);
		
		ga.prev();
		System.out.println("Etape précédente :\n");
		System.out.println(ga);
		
		ga.next(39);
		System.out.println("39 étapes suivantes :\n");
		System.out.println(ga);
		
		ga.prev(20);
		System.out.println("20 étapes précédentes :\n");
		System.out.println(ga);
		
		ga.reset();
		System.out.println("Réinitialisation :\n");
		System.out.println(ga);
*/	
		System.out.println("\n---- Retour sur exercice 2 : visualisation des grilles aléatoires ----\n");
/*
		System.out.print("Visualisation de grilles remplies à 25%, 50% et 75%...");

		Grille al1, al2, al3;
		ImageGrille igal1, igal2, igal3;
		AnimationGrille vgal1, vgal2, vgal3;

		al1 = new GrilleCirculaire(32, 32, 25, Evolution.CONWAY);
		igal1 = new ImageGrille("aléatoire 25%", al1, 800, 800, 1, 2);
		vgal1 = new AnimationGrille(igal1);
		vgal1.start();

		al2 = new GrilleCirculaire(32, 32, 50, Evolution.CONWAY);
		igal2 = new ImageGrille("aléatoire 50%", al2, 800, 800, 1, 2);
		vgal2 = new AnimationGrille(igal2);
		vgal2.start();

		al3 = new GrilleCirculaire(32, 32, 75, Evolution.CONWAY);
		igal3 = new ImageGrille("aléatoire 75%", al3, 800, 800, 1, 2);
		vgal3 = new AnimationGrille(igal3);
		vgal3.start();
		
		System.out.println(" ok\n");
*/
	}

}

/*

---- Exercice 1 ----

Test des règles de Conway :

- cellule entourée de 0 cellule(s) vivante(s) peut naître :  non  ; peut survivre :  non 
- cellule entourée de 1 cellule(s) vivante(s) peut naître :  non  ; peut survivre :  non 
- cellule entourée de 2 cellule(s) vivante(s) peut naître :  non  ; peut survivre : [OUI]
- cellule entourée de 3 cellule(s) vivante(s) peut naître : [OUI] ; peut survivre : [OUI]
- cellule entourée de 4 cellule(s) vivante(s) peut naître :  non  ; peut survivre :  non 
- cellule entourée de 5 cellule(s) vivante(s) peut naître :  non  ; peut survivre :  non 
- cellule entourée de 6 cellule(s) vivante(s) peut naître :  non  ; peut survivre :  non 
- cellule entourée de 7 cellule(s) vivante(s) peut naître :  non  ; peut survivre :  non 
- cellule entourée de 8 cellule(s) vivante(s) peut naître :  non  ; peut survivre :  non 

- cellule vivante entourée de 0 cellule(s) vivante(s) changera d'état : [OUI]
- cellule vivante entourée de 1 cellule(s) vivante(s) changera d'état : [OUI]
- cellule vivante entourée de 2 cellule(s) vivante(s) changera d'état :  non 
- cellule vivante entourée de 3 cellule(s) vivante(s) changera d'état :  non 
- cellule vivante entourée de 4 cellule(s) vivante(s) changera d'état : [OUI]
- cellule vivante entourée de 5 cellule(s) vivante(s) changera d'état : [OUI]
- cellule vivante entourée de 6 cellule(s) vivante(s) changera d'état : [OUI]
- cellule vivante entourée de 7 cellule(s) vivante(s) changera d'état : [OUI]
- cellule vivante entourée de 8 cellule(s) vivante(s) changera d'état : [OUI]

- cellule morte entourée de 0 cellule(s) vivante(s) changera d'état :  non 
- cellule morte entourée de 1 cellule(s) vivante(s) changera d'état :  non 
- cellule morte entourée de 2 cellule(s) vivante(s) changera d'état :  non 
- cellule morte entourée de 3 cellule(s) vivante(s) changera d'état : [OUI]
- cellule morte entourée de 4 cellule(s) vivante(s) changera d'état :  non 
- cellule morte entourée de 5 cellule(s) vivante(s) changera d'état :  non 
- cellule morte entourée de 6 cellule(s) vivante(s) changera d'état :  non 
- cellule morte entourée de 7 cellule(s) vivante(s) changera d'état :  non 
- cellule morte entourée de 8 cellule(s) vivante(s) changera d'état :  non 

---- Exercice 2 ----

Grille 5x7 (tableau) :

.OO..OO
.......
...OO..
..OOO..
......O

Grille 5x7 (aléatoire, 25%) :

..O...O
.....OO
....O..
..O..O.
.....O.

Grille 5x7 (aléatoire, 75%) :

O.OO.OO
OO.OO..
.OOOOO.
OO.OOOO
OOOOOOO


---- Exercice 3 ----

Grille :

.OO..OO
.......
...OO..
..OOO..
......O

case ( 0,  0) : '.' voisins : 1
case ( 2,  2) : '.' voisins : 3 changera
case ( 2,  3) : 'O' voisins : 4 changera
case (-1, -1) : '.' voisins : 0
case ( 5,  6) : '.' voisins : 1

---- Exercice 4 ----

Etat initial :

.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
..................OOO..................
..................O.O..................
..................O.O..................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................

Etape suivante (grille modifiée ? OUI) :

.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
...................O...................
..................O.O..................
.................OO.OO.................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................

Etape suivante (grille modifiée ? OUI) :

.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
...................O...................
.................OO.OO.................
.................OO.OO.................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................

Etape suivante (grille modifiée ? OUI) :

.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
..................OOO..................
.................O...O.................
.................OO.OO.................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................

Etape suivante (grille modifiée ? OUI) :

.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
...................O...................
..................OOO..................
.................O...O.................
.................OO.OO.................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................

106 étapes suivantes :

.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
............OO....OOO....OO............
............OO...........OO............
....OO...........................OO....
...O.O...........................O.O...
....O.............................O....
.............OOO.......OOO.............
............O..O.......O..O............
............O...O.....O...O............
...........OO.O.O.....O.O.OO...........
...........OO.OO.......OO.OO...........
.....OOO....OOO.........OOO....OOO.....
....O...O.....................O...O....
...O.....O...................O.....O...
...O.....O......OO...OO......O.....O...
...O.....O.....OO.....OO.....O.....O...
....O...O....O..O.....O..O....O...O....
.....OOO......OO.......OO......OOO.....
.................O...O.................
..................O.O..................
............OOOO.O...O.OOOO............
...........O....O.....O....O...........
...........O..O.........O..O...........
............OO...........OO............
.......................................

Sauvegarde dans clown-110.txt... ok

Visualisation de clown, oscillateur, galaxie, puffer, canon, floraison et grenouille... ok


---- Exercice 5 ----

Grille :

.OO..OO
.......
...OO..
..OOO..
......O

case ( 0,  0) : '.' voisins : 3 changera
case ( 2,  2) : '.' voisins : 3 changera
case ( 2,  3) : 'O' voisins : 4 changera
case (-1, -1) : 'O' voisins : 2
case ( 5,  6) : 'O' voisins : 2

Grille non circulaire, état initial :

.O.....
..O....
OOO....
.......
.......

40 étapes suivantes :

.......
.......
.......
...OO..
...OO..

Grille circulaire, état initial :

.O.....
..O....
OOO....
.......
.......

40 étapes suivantes :

....O..
.....O.
...OOO.
.......
.......

Visualisation de planeur, mathusalem et spacefiller... ok


---- Exercice 6 ----

Etat initial :

.O.....
..O....
OOO....
.......
.......

Etape suivante :

.......
O.O....
.OO....
.O.....
.......

Etape suivante :

.......
..O....
O.O....
.OO....
.......

Etape suivante :

.......
.O.....
..OO...
.OO....
.......

Etape précédente :

.......
..O....
O.O....
.OO....
.......

Etape précédente :

.......
O.O....
.OO....
.O.....
.......

39 étapes suivantes :

....O..
.....O.
...OOO.
.......
.......

20 étapes précédentes :

......O
O......
O....OO
.......
.......

Réinitialisation :

.O.....
..O....
OOO....
.......
.......


---- Retour sur exercice 2 : visualisation des grilles aléatoires ----

Visualisation de grilles remplies à 25%, 50% et 75%... ok

*/